apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seoul-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minlnim/project.git
    targetRevision: main
    path: seoul/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
